server:
  port: 7778
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victor-yangsheng/springcloud.git
          username: victor-yangsheng
          password: y1178855430
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka